### ISSUE TITLE
method

### ISSUE THREAD

**Issue by fega** [Zolmeister/js-solver#1]
hello, whst method the library uses for? thanks

**Comment by Zolmeister** [comment]
Please clarify

**Comment by fega** [comment]
Hello again Zolmeister, I was asking for the method used for your library to get the answers of the equations. 

For example Newton raphson method or so.

thanks man.

**Comment by Zolmeister** [comment]
Ah, this solver is very basic. It simply iterates and eval's equations, brute forcing a solution if given equations in the proper context ([source](https://github.com/Zolmeister/js-solver/blob/master/js-solver.js#L50)).

e.g. if `a=b+1`, given b=1 eval `a=1+1`, and replace other instance of `a` (`c=a+2`, turns into, `c=2+2`)
